name: yoyo_player
description: yoyo_player is a video player that allows you to select HLS video
  streaming by selecting the quality
version: 0.2.0
homepage: https://github.com/ko-htut/yoyo-player/
repository: https://github.com/ko-htut/yoyo-player/
issue_tracker: https://github.com/ko-htut/yoyo-player/issues/
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  orientation: ^1.3.0
  path_provider: ^2.0.1
  video_player: ^2.1.1
  video_player_web_hls: ^0.1.10
  wakelock: ^0.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
